# Generated by Django 4.2.5 on 2023-09-11 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "verbose_name": "Рецепт, добавленный в список покупок",
                "verbose_name_plural": "Рецепты, добавленые в список покупок",
            },
        ),
    ]
